### ISSUE TITLE
Option to change default category on opening the app

### ISSUE THREAD

**Issue by tobyps** [nextcloud/polls#1072]
We used Polls for our 200+ members of whicht a quarter already has access to our cloud.
For those without access it works good.
But those with access who didn't follow the direct link to the poll all had trouble finding it, because by default Poll opens with "relevant Polls" and they didn't realize they had to choose "public polls".

As I unterstand, we can already make sure the poll is in the "relevant" tab by inviting the users via the built in option but due to our mixed userbase (cloud and noncloud users)  that is not a viable option for us.

It would be great if the admins could change the default via an option. Maybe even have an options menu for the users as well where they can select their individual preference.
Alternatively if the App would remember which Category the user used last would work too.

Thx

**Comment by dartcafe** [comment]
Since you may have different entry points to the list, it is difficult to realize. I added an option to the poll configuration, where you can force a poll to be displayed in the relevant filter for all users. Hope this meets your expectation.

This is because there was the exact opposite request (#865), to hide public polls, because it confuses users.

**Comment by dartcafe** [comment]
![grafik](https://user-images.githubusercontent.com/26707476/92139395-f759d080-ee0f-11ea-9f95-5cbface2b182.png)
