### ISSUE TITLE
Add possibility to edit poll options

### ISSUE THREAD

**Issue by reimer-atb** [nextcloud/polls#1079]
**Is your feature request related to a problem? Please describe.**
When adding options to a poll you sometimes have to apply changes to an option you have already created. But there is no way to change the text (or date/time) of an option. You have to delete the option and recreate it again.
This is especially cumbersome in text polls where your poll options should appear in a specific order.
Because adding an option always appends it to the end of the list of options and you have to manually drag it into the correct position.

**Describe the solution you'd like**
I would like to have an option to edit an existing option for a poll. I.e. add an edit icon next to the delete icon for each poll option.

For text-based polls clicking the edit icon would turn the displayed string into an input field and also show an "ok" and a "cancel" icon.
Clicking "ok" will submit the changes to the text and display the new text in the poll option.
Clicking "cancel" will ignore any changes to the text and display the original text in the poll option again.

For date polls clicking the edit icon would show the date / and time picker to change the date and time just like when adding a new option. It would also display an "ok" and a "cancel" icon with the same functionality as described above.

**Describe alternatives you've considered**

**Additional context**

**Comment by dartcafe** [comment]
The result between both ways is exactly the same. What is the advantage of the suggested way compared to the current one? How often are poll texts subject of a change?

Your suggested change meets limitations of space and adds complexity to the app.

The current way clarifies, that options cannot be changed, just deleted and created. This is by intention.

A little explanation why: In text polls, votes are compared against the exact text of an existing option. If the text option changes, the vote will get invalid and will be removed.

**Comment by philipreimer** [comment]
My use case is the following: I wanted to create a poll with around 10 options, where order of the options was important.
Basically I was trying to use a text-based poll as a date poll because I needed to define a time duration - see #492 .
During preparation of the poll I noticed that I had to change some of the options.
I could not edit them but had to delete them and create new ones, which were appended at the end of the list of options.
I then had to manually re-arrange the options to get them into the correct order. It would have been faster if I had been able to just change the text of the existing options.

> Your suggested change meets limitations of space and adds complexity to the app.

The date poll options have a delete and clone button. I think there is space enough to add an edit button for the text-based options, as well.
One could even use the same process with a modal window to change the text (like when cloning a date option).

I would only want to use that feature while preparing a poll. Not when the poll has been published and the first vote has been cast.

> If the text option changes, the vote will get invalid and will be removed.

What happens if I delete an option while the poll is already running? Does that also remove the votes?
Shouldn't this be prevented in general?

**Comment by dartcafe** [comment]
> I then had to manually re-arrange the options to get them into the correct order. It would have been faster if I had been able to just change the text of the existing options.

I think I understand your use case. But I guess, this is not on a regualr basis. 

> The date poll options have a delete and clone button. I think there is space enough to add an edit button for the text-based options, as well.

It is not only a question of free space. Especially for text polls, which usally will have longer texts. It is also a question of UX. 

And we need another dialog to get this edited, or make the entry editable. More code, more tests, more complexity. If this use case would be a regular one, which costs much time for all users, it my be more worthy. 

> I would only want to use that feature while preparing a poll. Not when the poll has been published and the first vote has been cast.

Creating a poll is done with the type and the title. After that everything is editing. 

> What happens if I delete an option while the poll is already running? Does that also remove the votes?

The votes do not get deleted, they are just not visible, because there is no option, where they can be related to. You can test this, when shifting the options in a date poll or delete an option and recreate the excact one as a new option.
