### ISSUE TITLE
Public Link should work not only for shared members

### ISSUE THREAD

**Issue by martinelkb** [nextcloud/polls#1153]
### What is going wrong?

Public Link should work for everyone, not only for shared members

**To Reproduce**
1. Go to 'Öffentlichen Link hinzufügen' (Create a public Link)
2. Click on 'Link in Zwischenablage kopieren' (Copy to the clipboard)
3. Send the Link to a another person that has an account, but was not specially added to "Freigaben" (Shares)

**Expected behavior**
The public Link should open to the shared poll for users that are previously logged (or lead in the first step to a login page).

Public Link Link should work as an invitation to the poll. 

**Behavior**
Logged User gets the Message if following the Link
`"No existing polls." : "Keine Umfragen vorhanden.",`

**Screenshots**
![poll_bug_issue](https://user-images.githubusercontent.com/72702362/95690492-8f6d8580-0c18-11eb-9e8e-9b001962f356.png)

**Nextcloud/ownCloud version:** (see Nextcloud admin page)

Version "19.0.3",

**Comment by dartcafe** [comment]
That would break the logic and would cause a lot of developing and testing. We rely on the defined share settings for internal users. Either invite the user directly, share with a group or set the poll to public (`Visible to other users`). 

If a poll is `Hidden to other users` no one can enter the poll exept users who are invited to the poll (or not logged in users via a public share link). 

I see the break in the logic, you raise. But I would see the break in the settings 'hidden poll' and entering it via a public link.

I leave this issue open and put it in the backlog. But I cannot proove, when we are able to go in this.

**Comment by brtptrs** [comment]
Many of out users have problems with this behaviour. 

Say a user with a NC account receives a public-link invitation to a poll via mail, chat or on a private web page. This is "internal" since one does not want everybody to see the poll. 

Example:
At a conference I want to start a poll but don't know who has a NC account, it is a huge effort to split the invitation between people with and without accounts.

- The user follows the link
- A dialogue Allows the option: I already have an NC account
- The user logs in
- Now the user gets a "poll does not exist" error.

I'm pretty sure that this used to be different. The behaviour the users expect is the same as elsewhere in NC i.e. with file sharing.

**Comment by dartcafe** [comment]
Nice use case. I think, we can achieve this by adding a user to the shares, when he enters the poll via a public share token and the poll is a hidden poll? 
Additionally skip invitation mail or the unsent invitation status.

**Comment by sress** [comment]
@dartcafe 
Thanks!
We already had some users wondering why they got the `poll does not exist` error.

A fix would be much appreciated.

**Comment by dartcafe** [comment]
As I am changing the share system internally, this depends on the circles integration, which I plan for version 1.6. Good chance to get this done in this version too.

**Comment by martinelkb** [comment]
> As I am changing the share system internally, this depends on the circles integration, which I plan for version 1.6. Good chance to get this done in this version too.

Cool!
