### ISSUE TITLE
Possibility to make a poll truely anonymous even for the poll creator

### ISSUE THREAD

**Issue by annievoss** [nextcloud/polls#1221]
**Is your feature request related to a problem? Please describe.**
When we conduct e. g. elections of people, no one is allowed to see who has voted for whom, not even the poll creator.

**Describe the solution you'd like**
When the poll creator marks the poll as anonymous, the names of the respondents should neither be asked nor displayed.
Only the number of participants should be displayed.

**Describe alternatives you've considered**
If something like a name is necessary, a random number could be generated automatically.

**Comment by dartcafe** [comment]
This is by intention, see #926 and #953

**Comment by dartcafe** [comment]
Reading your request again, I have to make clear, that this app is not designed to make election polls.

**Comment by annievoss** [comment]
that was just a possible usage. Also I don't know why the option is called anonymous, when it's clearly not fully anonymous. In other poll apps the option ist called "hide participants" and "hide votes".

**Comment by Sohalt** [comment]
I agree that polls is not a voting application. Right now everybody can submit an arbitrary number of votes and it is also not secure enough for anything actually important (the votes are stored unanonymized in the database and the anonymization only happens in the view layer).
Nonetheless I would like to have the option of fully anonymous polls for things not as important as elections, but where participants might still be reluctant to reveal their preferences.
I also agree, that the current "anonymous" option is a bit of a misnomer. Maybe "hide votes from participants"?

**Comment by dartcafe** [comment]
There is no value in an "true anonymous" option, as long as the owner can remove and add it any time. Therefore we added a sentence to the poll description. 

Of course we can talk about wording, but this option was called anonymous since the very first version.

**Comment by impilarcz** [comment]
Semi-anonymous polls are useless as long as any participant can see the voters name. This is hard to explain users and they have trust issues (just my feedback). 

Please remove it completely or just add warning message that it is one way setting and disable unanonymization. It is not so hard to disable clicking on it again (frontend) and check in backend... 

I know that adding description to current functionality was the easiest solution, but kind of insufficient. Thank you in advance! :-)

**Comment by dartcafe** [comment]
The fact that anonymous polls are used and requested, shows that it is not useless and so we will not remove it. And the owner of a poll has the complete power over the poll by design. 

If we make the poll unrevertible anonymous for the owner, we also have to renounce notifications, invitations/shares, poll changing. Otherwise names and participants will get leaked in different places.

**Comment by alexanderdd** [comment]
Ok, I understand that the polls app is not and does not want to be a voting application.

I was also hoping it is possible to do true anonymous voting :disappointed: Our organisation needs a voting solution, and many other services are not usable for us because of privacy regulations.

**Comment by dartcafe** [comment]
You can use a full anonymous vote, if you use a public poll. But you will lose the ability to ensure, that a user can only cast one vote.

To become real anonymous we have to make sure, that the vote cannot be connected to a user account after the vote. This is not possible with the current structure. And because of this, we should not pretend that polls can be anonymous.
