### ISSUE TITLE
Hide email address when no SMTP server is configured

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#1419]
* No SMTP: Wow, didn't believe, that there are installations without SMTP configuration. But you are right, if no SMTP is configured, the email address (as option for a public poll) is confusing, because of a user's expectation, which can't be fullfilled. But I fear we have more to do then, because at least sharing is relying on emails right now. We should have a separate issue for that. 

_Originally posted by @dartcafe in https://github.com/nextcloud/polls/issues/1271#issuecomment-749237575_

**Comment by tobyps** [comment]
It is not always necessary to configure the SMTP server to be able to send Emails.

My webhoster for instance doesnt need it and NC will send Emails without configuration over no-reply@yourdomain without issues.

Such an option could confuse users of those clouds, especially because they might not be that experienced in the first place.
