### ISSUE TITLE
Hide participants from poll owner

### ISSUE THREAD

**Issue by FlxVctr** [nextcloud/polls#1422]
**Is your feature request related to a problem? Please describe.**
In some cases, e.g. elections, the owner of the poll should not know who voted for what.

**Describe the solution you'd like**
Add an option to hide the participants' names from the owner of the poll.

**Comment by dartcafe** [comment]
We discussed this a few times. Polls is not intended to support elections or similar confidential polls. Otherwise we have to design this down to the persistence layer. Because of this, we should not pretend that true anonymity is possible. If we want to achieve this we have to start the application desing from the bottom up, beginning ith the persistence layer.

So sorry for a no to this request. 

If you want an more anonymous poll, open a public poll and let the participants use pseudonyms. 

See also https://github.com/nextcloud/polls/issues/926#issuecomment-626351802
