### ISSUE TITLE
v1.8.2 and v1.8.3 not in the app store

### ISSUE THREAD

**Issue by brtptrs** [nextcloud/polls#1548]
Thanks for the new releases!
Is there a specific reason why they an not showing up in the app store and upgrade lists?

**Comment by dartcafe** [comment]
As always, the app store release has a delay due to the availability of @v1r0x 
I asked him, if he is able to push the release. I have no access.

**Comment by brtptrs** [comment]
Thanks for the feedback

**Comment by jotoeri** [comment]
So - just as a trigger to @v1r0x - How do you think about giving @dartcafe the rights to upload releases? Effectively he does the releases anyways, no? And it might even relax your todo-list a bit...? 😉 
I honestly don't know exactly how it works, but somehow registering a user as co-maintainer should suffice afaik. At least i'm able to push forms-releases, while beeing listed as co-maintainer....

(And to be honest - i'm asking also a bit as i'd really like to get the performance-fix on 1.8.2. into my instance through the app-store 🙈 )

**Comment by v1r0x** [comment]
@jotoeri I don't know if it is possible to create a second certificate for a different user or if I have to give my certificate to @dartcafe to sign the releases in the appstore?
Nevertheless, I plan to give @dartcafe the rights to release in the appstore, because he is (for a longer time now) developer and maintainer of the app :smiley: 

For the 1.8.x releases I need access to my home computer, which is currently in one of the many boxes in my new flat :see_no_evil: Definitely this week, hopefully even today :crossed_fingers:

**Comment by jotoeri** [comment]
>  If there are cases where this is not feasible and multiple certificates are required Nextcloud can create them on a case by case basis.

Hm, according to the docs it should be possible to have a second cert... Maybe just give it a try by asking on the community chat or on the CSR-Repo...? 🤔

**Comment by dartcafe** [comment]
1.8.3 is avaiable in the app store
