### ISSUE TITLE
Interface 'OCP\AppFramework\Bootstrap\IBootstrap' not found in V1.9.5 on NC19

### ISSUE THREAD

**Issue by JohnWalkerx** [nextcloud/polls#1710]
### What is going wrong?
**Describe the bug**
If you install the app on NC 19.0.12, you get following error:
```
Interface 'OCP\AppFramework\Bootstrap\IBootstrap' not found at /var/www/nextcloud-laj/apps/polls/lib/AppInfo/Application.php#37
```
On an update to the version 1.9.5 the Nextcloud instance goes into maintenance mode and wants you to run the instance upgrade.

**To Reproduce**
Steps to reproduce the behavior on update:
1. Go to Apps
2. Update Polls App to version 1.9.5
3. Error Message appears that something went wrong

Steps to reproduce the behavior on new installation:
1. Go to Apps
2. Install Polls App with version 1.9.5
3. Error Message appears that something went wrong

**Expected behavior**
App installs successful on update or new to version 1.9.5

### Information about your polls installation
**Polls version?** (see apps page)
1.9.5
**Fresh installation or update from a prior version (from which one)?**
update (version unknown) and new installation after removing it.
**How did you install this version?(Appstore or describe installation)**
Appstore
### Information about your Instance of Nextcloud

**Nextcloud version:** (see Nextcloud admin page)
19.0.12
**List of activated apps:**
(Polls is currently deactivated on my instance because of this issue)

<details><summary>List of activated apps</summary>

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - announcementcenter: 3.8.1
  - apporder: 0.12.0
  - audioplayer: 2.13.1
  - bookmarks: 3.4.9
  - bruteforcesettings: 2.1.0
  - calendar: 2.0.5
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.5.1
  - contactsinteraction: 1.0.0
  - cospend: 1.0.5
  - dav: 1.15.0
  - deck: 1.2.7
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_external: 1.10.0
  - files_markdown: 2.3.2
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - forms: 2.2.4
  - gpxpod: 4.2.2
  - groupfolders: 7.1.2
  - impersonate: 1.6.1
  - issuetemplate: 0.7.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.3
  - maps: 0.1.6
  - nextcloud_announcements: 1.8.0
  - notes: 3.6.4
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - previewgenerator: 2.3.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - ransomware_protection: 1.7.1
  - richdocuments: 3.8.2
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.10
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - tasks: 0.13.6
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_totp: 5.0.0
  - twofactor_u2f: 6.0.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - bbb
  - encryption
  - onlyoffice
  - phonetrack
  - polls
  - recommendations
  - sharerenamer
  - user_ldap
```
</details>

**Nextcloud configuration:**

<details><summary>Configuration (config/config.php)</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.example.de\/",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "19.0.12.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 1.5
        },
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "logtimezone": "Europe\/Berlin",
        "loglevel": 0,
        "log_rotate_size": "10485760",
        "default_language": "de",
        "default_locale": "de_DE",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "30, 90",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "calendar"
        ],
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "theme": ""
    }
}

```
</details>

### Server configuration

**Database:**
mysql 8.0.25

**PHP version:** 
7.3.28-2+ubuntu20.04.1+deb.sury.org+1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Device:**
Desktop 

**Browser:**
Firefox 89.0

**Comment by dartcafe** [comment]
Great. I missed the imcompatibility to version 19. 
@v1r0x Is 1.9.5 withdrawable from the appstore? Since NC19 runs out of support once NC22 is out, it doesn't make sense to work on a compatibility. I'll update the stable-1.9 branch to the required minimum NC version and raise to 1.9.6.

@JohnWalkerx I recomment updating to at least NC20, since we will not get back the compatibility. Sorry for the mess.

**Comment by unnilennium** [comment]
same issue, here, unable to upgrade to NC20 because of requirement of mysql are not met on my server.
Can you at least unroll the update to it is not offered on update system anymore ?

**Comment by dartcafe** [comment]
@unnilennium If the db is not migrated, you can manually install https://github.com/nextcloud/polls/releases/download/v1.8.3/polls-1.8.3.zip.

If the db is already migrated, it is a little bit more complicated.

**Comment by unnilennium** [comment]
> @unnilennium If the db is not migrated, you can manually install https://github.com/nextcloud/polls/releases/download/v1.8.3/polls-1.8.3.zip.
> 
> If the db is already migrated, it is a little bit more complicated.

still I remain with the risk to break my production instance as long as this update is available.
could a 1.9.5.1 being a copy of 1.8.3 be released just to hide the 1.9.5 ?

**Comment by dartcafe** [comment]
> could a 1.9.5.1 being a copy of 1.8.3 be released just to hide the 1.9.5

This breaks the semver logic and will lead to confision, because 1.9.5.1 would be a downgrade. 

There will no be any harm to your data. If the app throws errors, because some db migration happened, I can lead you through the process, as long as you have access to your database.

**Comment by dartcafe** [comment]
If you have access to your database and the filesystem: 

Filesystem:
1. disable and remove polls (The data will be preserved)
2. extract the contents of https://github.com/nextcloud/polls/releases/download/v1.8.3/polls-1.8.3.zip to the app-folder of your installation

Database:
1. Navigate to the table `oc_polls_polls` and delete the columns
* `allow_proposals`
* `use_no`
* `proposals_expire`

2. Navigate to the table `oc_polls_options` and delete the columns
* `owner`
* `released`

3. Navigate to the table `oc_migrations` and delete the record


app | version
-- | --
polls | 0109Date20210323120002


4. enable polls
5. ensure to not start the update to polls 1.9.x



But again, I recomment to upgrade away from NC19.

**Comment by unnilennium** [comment]
no harm to my data, but harm to the business due to downtime on every occasion one will trigger the update and leave the nextcloud instance unavailable.
I know this would be a regression, but as you do not want to try to fix it to have new elements in 1.9,5 compatible with NC19 (and I can understand that), then this is the less worst approach, leave the NC19 branch stable without risk one will put its server in maintenance mode without easy exit.

As you suggest to downgrade to 1.8.3, just help people to do so and not fall in the gap, and make a copy of 1.8.3 with higher versioning than 1.9.5 and compatible only with NC19 and under, so you do not mess with people on NC20 and higher.

Thanks for the how to fix the DB (this might help a few people if you do not fix the situation). I was lucky to have daily backup of db and files for the two times poll update left my server in maintenance mode : 1.9.4 and 1.9.5 .......

again please consider the regression, not doing so is like leaving an open hole in the road with a sign "mind your step"  at the bottom of the hole. Just patch the hole before other fall in it, please. And yes, we understand you suggest we should use another street ....

**Comment by dartcafe** [comment]
There is a replavement, to avoid this. It depends on the avaialbility of @v1r0x See comment above https://github.com/nextcloud/polls/issues/1710#issuecomment-856945590

**Comment by dartcafe** [comment]
BTW: You can manually prevent the update by raising the version number from 1.8.3 to 1.9.5.1 in 
https://github.com/nextcloud/polls/blob/f7953085e19db0e45b4a4c50e6cf46ffb63e37c9/appinfo/info.xml#L8

**Comment by dartcafe** [comment]
@v1r0x Any cahnge you can shortly remove 1.9.5 and replace it with a build from the 1.9.6 tag?

**Comment by dartcafe** [comment]
Since the Update from 1.8.3 to 1.9.5 chaged the database, I will make a special update for NC19 to revert to 1.8.3 and migrate the database back to the mathing setup. It will come at the weekend (possibly tomorrow, if I have time enough to test this.) This will mix up the semver a little bit, but individually fixes can produce more harm. 

The Plan: 
* 1.9.5 currently is NC19 - 21
* 1.9.6 is NC20 - 21
* 1.9.7 will internally be a version 1.8.4 but gets 1.9.7 and will be NC19 only.
This way also manually fixes as described above should work. 

Unfortunately I have no time today for this. 

@v1r0x If you would be able to fire the releases into the appstore, we can get rid of this mess this weekend.

**Comment by dartcafe** [comment]
I added a pre-release to address the update error on NC19. If anyone is able to test the update; Instructions under #1730. Please report any result there, also. 

Thanks in advance
