### ISSUE TITLE
Remove deprecated methods

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/polls#179]
ToDo:

- [X] Remove deprecated methods
- [X] Remove loose comparism in PHP
- [X] Add model protperty types
- [X] Test against Nc and oC
- [X] Add occ app:check-code to Travis CI

**Comment by v1r0x** [comment]
I think this depends on the versions we want to support. At least NC11 should be supported. Maybe even NC10. Any other opinions? @dartcafe @splitt3r

**Comment by splitt3r** [comment]
Yes you are right. The info.xml lists NC 11 as min version but we have to also check against oC. I think i will check wich methods are deprecated in all our supported systems once i have the time to investigate.

**Comment by dartcafe** [comment]
I would only support NC11 and up. With the release of NC13, we should drop support for NC11, because there are some major changes. I.e. the support of SCSS. 

OC10 works with one issue: The plus sign for new polls is missing. 

I have setup some instances for OC10, NC11-13. If you like, you can test there. I will put the 0.8 there.

**Comment by xXSTrikeXx** [comment]
@dartcafe there? Where I can test?

**Comment by dartcafe** [comment]
Register at https://nc12.yagst.de. I will transfer the users to the other instance manually including the mail address.

**Comment by splitt3r** [comment]
@v1r0x @dartcafe i started some clean up over at https://github.com/splitt3r/polls/tree/cleanup maybe we should move that branch over to the nc repo so you can better track the progress and contribute?

**Comment by v1r0x** [comment]
With great power comes great responsibility :wink: 
Have fun :D
