### ISSUE TITLE
Repair link in email notification working

### ISSUE THREAD

**Issue by rubo77** [nextcloud/polls#1902]
**Steps to reproduce the behavior**
1. create a poll
2. Subscribe to notifications 
3. let someone else vote
4. use the direct link to the vote in the email (e.g. https://next.somewhere/index.php/apps/polls/vote/5 )

that link does not work, it should be e.g. https://next.somewhere/apps/polls/vote/5

## Information about your polls installation
**Polls version:** 3.0.0

**Fresh installation or update from a prior version (from which one)?**

- [ ] First time install
- [x] Update from a prior version
  Version number of the previous version: I don't remember (it was the one before)

**How did you install this version?(Appstore or describe installation)**

- [x] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** 21.0.4

<details>
<summary>List of activated apps</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>
<details>
<summary>Nextcloud Configuration</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server configuration (decide, if you think it is helpful)

**Database:**
- [ ] MySql version:
- [x] MariaDB version:
- [ ] PostgreSQL version:
- [ ] Oracle version:
- [ ] SQLite:
- [ ] Other (add name and version):

**PHP version:**
- [ ] 7.3 or lower
- [x] 7.4
- [ ] 8.0

I use a docker image

### Client configuration
**Device:** 
- [x] PC (linux ubuntu thunderbird)
- [ ] Mac
- [ ] Mobile phone
- [ ] Tablet

**Browser:** 

- [x] Firefox version: 90.0
- [x] Chrome version: ?
- [ ] Safari version:
- [ ] Other (add name and version):

## Logs

<details>
<summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
<summary>Browser console log</summary>

```
Insert your browser console log here
```

</details>

<details>
<summary>Other browser logs</summary>

```
Insert additional logs from your browser here
```
</details>

**Comment by dartcafe** [comment]
See this https://github.com/nextcloud/polls/issues/1255#issuecomment-752378092

**Comment by nursoda** [comment]
I also hit this – and am irritated. The documentation is quite unclear about side effects, especially as I'm nut using Apache but NGINX. But I assume that this merely fixes that the link including "/index.php" will be rendered again. I see the error in creating a link containing "/index.php" in the first place. Polls should be able to question some API whether or not to include "/index.php" or not … please try to get that information / API from the core team.

**Comment by dartcafe** [comment]
We can't help here, unfortunately. 

Polls doesn't care about the base url and if index.php is inserted or not and it doesn't insert it. The full URL is generated by the core (via CLI) using the API. 

You do not even find the string `index.php` in the whole polls code.

**Comment by nursoda** [comment]
I'm not convinced yet. Thing is: `/index.php` or not should work either way and it works for me e.g. for settings like `/index.php/settings/user` just as `/settings/user`, and for all apps, like `/index.php/apps/files` and `/apps/files` – but not for `/index.php/apps/polls`.

For reference: My system is using NGINX based on this [NGINX config](https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html). Setting `'htaccess.RewriteBase' => '/',` as proposed in the [server manual](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#proxy-configurations) seems unnecessary with this NGINX config, setting it did not change anything – neither concerning pretty URLs (was without `/index.php` even without this setting) nor the generated links (that stay with `/index.php`). I even doubt that `'htaccess.IgnoreFrontController' => true,` does make any difference for the above NGINX config, at least it didn't for me.

**Comment by dartcafe** [comment]
> I'm not convinced yet. Thing is: `/index.php` or not should work either way

This should be handled by the server, which does rewriting, not by the app.

See: Polls asks the server for the base url and gets https://domain.tld/ 
This is the base url for the vue router, which manages the routing. Any inserted index.php resutls in a route, which is not recognizable and is handled as an unknown route. 

If you have any hint, how to solve this: Any advise or hint is welcome.

**Comment by nursoda** [comment]
René, I don't think it's about which URL is created but how the clicked-in-the-email-URL is handled by the app (or by the server).

> Any inserted index.php resutls in a route, which is not recognizable and is handled as an unknown route.

If that is true, why do all other apps still work fine even with `/index.php` in a URL request?

**Comment by dartcafe** [comment]
> If that is true, why do all other apps still work fine even with `/index.php` in a URL request?

Again: If you have any hint, how to solve this: Any advise or hint is welcome.

**Comment by dartcafe** [comment]
And: referring to `'htaccess.IgnoreFrontController' => true,`:

It seems to do exactly, what it should. I.e.: 

https://github.com/nextcloud/server/blob/62a814f4fbdec485e97e6b55a8320a02ced488bb/lib/private/URLGenerator.php#L125

**Comment by dartcafe** [comment]
And and: After looking to it the 100th time: 

Since polls needs to request the current route name to tell if it is a public route or not and if we called the vote page or the list, it must rely on the correct base URL as returned from the core. 

I assume, the problem here is the incorrect (or not happening) rewrite, because any URL with index.php should be rewritten to a clean URL by the web server.

**Comment by nursoda** [comment]
Sorry for my pushing and many thanks for your patience and answer! It doesn't explain why other apps render fine even with `/index.php` and polls doesn't – but this is the wrong place to ask that question. I'll ask that questions in the forum, I'll reference to this bug and if there are ideas/results, I'll post them here.

**Comment by dartcafe** [comment]
No problem. As long as no one feels offended, any discussion is welcome. In th and, I am interested in solutions.

#### Just to explain the issue here, as far as I understood
If the instance is configured to use clean URLs: 
* The core API returns `https://domain.tld` as the base route.
* Any valid route build with the pattern `https://domain.tld/apps/polls/{subroute}` is recognized by the vue router and the named route is set. This way i.e. `https://domain.tld/apps/polls/s/{token}` is recognized as the named route `publicVote`. 
* But the route `https://domain.tld/index.php/apps/polls/s/{token]` is not recognized by the vue router and no named route is returned.
* In the result, the decision for the used components based on the route name is not possible, because we have no nemed route.

As long as an app doesn't care about deciding upon the named route, this is no problem because when changing the route the correct clean URL is linked (you can check that with the deck app.

IMHO the task for ensuring, the route is clean, is to be done by the webserver with a correct rerouting. 

The other problem is, that if clean urls are configured, the CLI (triggered i.e. by the cron) doesn't know, that the clean URLs are configured. AFAIU setting `'htaccess.IgnoreFrontController'` => true, solves this problem. 

If this has side effects, is unclear to me, but since some people solved this issue with setting this config parameter, I guess, it has not (regardless, if apache or nginx is used).

> If that is true, why do all other apps still work fine even with `/index.php` in a URL request?

Some more examples, where the index.php produces problems: 
* https://domain.tld/index.php/apps/collectives --> Produces error: `Collective not found: index.php`
* https://domain.tld/index.php/apps/mail/ --> doesn't load as well
