### ISSUE TITLE
Polls are auto archived each morning 

### ISSUE THREAD

**Issue by ceryo** [nextcloud/polls#2111]
Dear All,
polls is auto archiving all polls each morning. In Nextcloud forum was suggested  to disable auto archive, but I don't know where and how. Does the next update solve this issue?

Details:
Nextcloud version: 22.2.3
Operating system and version : 20.04
nginx version: 1.21.4
PHP version : 7.4.3
Polls version: 3.3.0

**Comment by dartcafe** [comment]
> polls is auto archiving all polls each morning. 

Polls 3.3 has an error, where polls without an expiration date get archived every day. 

> In Nextcloud forum was suggested to disable auto archive, but I don't know where and how. 

/settings/admin/polls-admin
![grafik](https://user-images.githubusercontent.com/26707476/143721143-70306596-e48e-4e52-b127-0eeab977d08f.png)

Does the next update solve this issue?
Yes. The bug is fixed in 3.4.0

**Comment by ceryo** [comment]
Great, thanks a lot!

**Comment by dartcafe** [comment]
Issue is fixed with lates release (3.4.0)
