### ISSUE TITLE
Error logs repeated every 3 min

### ISSUE THREAD

**Issue by CATER-COM** [nextcloud/polls#2133]
Hi,

I have installed polls since somme fex days and every 2-3min I have this 3 errors line appearing in my nextcloud log : 

```
[no app in context] Error: Argument 1 passed to OCA\Polls\Notification\Notifier::getActor() must be of the type string, null given, called in /home/owncloud/apps/polls/lib/Notification/Notifier.php on line 123
​[PHP] Error: Undefined index: actor at /home/owncloud/apps/polls/lib/Notification/Notifier.php#123
[PHP] Error: Undefined index: pollTitle at /home/owncloud/apps/polls/lib/Notification/Notifier.php#122
```

Do you know what is wrong ?

**Comment by dartcafe** [comment]
Should not happen. There seems to exist a notification (in table oc_notification) for a poll_id that doesn't exist anymore.

**Comment by CATER-COM** [comment]
Ok I will check the table

**Comment by CATER-COM** [comment]
I removed 3 lines from the table. The user concerned was one of my colleague wich will be no longer connected until monday. So I'll check monday if the problem is solved.

**Comment by dartcafe** [comment]
Any more information or can we close this?

**Comment by stepka0815** [comment]
I have a similar phenomenon since today. The following 3 messages repeat several times in direct succession (3 - 9 times) and then there is a pause of 3 - 5 minutes until the whole thing starts again from the beginning:

`[no app in context] Error: Undefined array key "pollTitle" at /var/www/nextcloud/apps/polls/lib/Notification/Notifier.php#122`

`[PHP] Error: Undefined array key "actor" at /var/www/nextcloud/apps/polls/lib/Notification/Notifier.php#123`

`[PHP] Exception: OCA\Polls\Notification\Notifier::getActor(): Argument #1 ($actorId) must be of type string, null given, called in /var/www/nextcloud/apps/polls/lib/Notification/Notifier.php on line 123 in file '/var/www/nextcloud/apps/polls/lib/Notification/Notifier.php' line 91`

Do you have any idea what this could be and how I could fix the problem?
Deactivation, removal and reactivation have not changed the phenomenon.

**Comment by dartcafe** [comment]
To remove the error, you have to identity and delete the broken record (app = 'polls') in the database table `oc_notifications`. 

If possible, please export the record before deletion and post it here, so I have a sample to understand the issue. 

You can also drop the record here: https://nc.yagst.de/s/NqBZfxH7B82qpSm

**Comment by stepka0815** [comment]
Thanks and very nice. 
Otherwise, I would have had to organize support, as I lack the experience to clean up the database at the technical level requested. 
In case you are still interested, here is a file with the documentation of the 3 error messages in different formats that I had just finished when your last message arrived. 
Can you already estimate when you will be able to provide the fix, approximately?

[Polls – 3 constantly repeating error logs (documentation).pdf](https://github.com/nextcloud/polls/files/7840466/Polls.3.constantly.repeating.error.logs.documentation.pdf)

**Comment by dartcafe** [comment]
The fix will come with the new version. Currently there is no DOA, but at last when NC23 is out.

**Comment by stepka0815** [comment]
One more question: 
What exactly did you mean by "...but at last when NC23 is out". My understanding is that NC23 is out because I am currently using it [Nextcloud Hub II (23.0.0)] and the problems with polls occurred in that context.
Or haven't I correctly understood "when NC23 is out"?

**Comment by dartcafe** [comment]
replace 23 with 24
