### ISSUE TITLE
Check users mail by sharing 

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/polls#2264]
See this issue: #2253

if the owner share the poll with an email which exists in the database and the user is still logged in, the poll shows a error 404

Original post:
Hey,

I have tested it and found the problem. Some users told me that some users can't vote for a poll by an mail share. I tried to reproduce this.

The problem is (all users are LDAP accounts):
- **User A** created a poll
- **User A** shared the poll with **User B**, **User C**, **User D**...
- Now he typed in **user-h@example.com** and send the invitation. But the **User H** has an account!
- The **User H** see the mail and clicked on the link in it. The User H is logged in to NextCloud and the error appears
- If the **User H** logged out and use the link again it works

![image](https://user-images.githubusercontent.com/1473674/153709109-366b60f2-eca1-4e39-9543-5d23303a9eb1.png)

So the problem is that the accounts are not linked. We should check: If user mail is stored in NextCloud, then link it to the user account. If not, then the external flow is used.

I hope you can understand that :)

Thanks

**Comment by dartcafe** [comment]
This was only a display issue, since the search already returned users, where the search string matches the users' email address. 

The email address is now part of the description od users and contacts.

![grafik](https://user-images.githubusercontent.com/26707476/153961642-b8565ccf-6413-4a4e-b8a2-f7d7890b8603.png)
