### ISSUE TITLE
Invited via Link cannot Change

### ISSUE THREAD

**Issue by fabsn19** [nextcloud/polls#2391]
Users who were invited via a link and do not have a Nextcloud account cannot change their survey results after closing the website.  Is there a way in the options?

**Comment by dartcafe** [comment]
Please describe your problem a little bit more precise, or fill out the form after [creating an issue](https://github.com/nextcloud/polls/issues/new?assignees=&labels=&template=bug_report.md) instead of deleting it.

**Comment by fabsn19** [comment]
I created a date poll and invited people via a link.  The invitees cannot change their vote once they have voted, even if an email address has been provided.  Small example "Fritz" took part in the poll and would like to change his vote. On the poll page he was asked to enter his name because "Fritz" is already taken or reserved is displayed.  I just tested it again and you updated it today so that your name will be saved in the cookie for 30 days

**Comment by dartcafe** [comment]
A better place for usage problems is the [nextcloud forum](https://help.nextcloud.com/c/apps/polls/94).
In a public poll it is only possible to change the votes, when using the private link, which is generated upon registration.
Since 3.6.1 a cookie keeps the token, so that a user is able to reenter using the public link.

I think, we can close that.
