### ISSUE TITLE
Nextcloud 23 - Polls are Private and cannot be shared

### ISSUE THREAD

**Issue by jandr** [nextcloud/polls#2395]
After creating a poll on Nextcloud 23, it appears as private. When I try to publish it by sharing it, the share tab appears blank, as can be seen in the screenshot:

![image](https://user-images.githubusercontent.com/8058880/165805395-bb9950f8-0df2-48f8-a656-854145659eca.png)

## Information about your polls installation
**Polls version:** 3.6.1

- [ ] First time install
- [ ] Update from a prior version
  Version number of the previous version:
- [x] Not sure. Polls were working 1 year ago, and have not used since then (I did not have NC 23 then)

- [x] Installed from the appstore
- [ ] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** Nextcloud Hub II (23.0.4)

**Database:**
- [ ] MySql version:
- [x] MariaDB version: 10.5.15
- [ ] PostgreSQL version:
- [ ] Oracle version:
- [ ] SQLite:
- [ ] Other (add name and version):

**PHP version:**
- [ ] 7.3 or lower
- [ ] 7.4
- [x] 8.0

### Client configuration
**Device:** 
- [x] PC
- [ ] Mac
- [ ] Mobile phone
- [ ] Tablet

**Browser:** 

- [x] Firefox version: 99.0
- [ ] Chrome version:
- [ ] Safari version:
- [ ] Other (add name and version):

**Comment by jandr** [comment]
It does not work in my browser (Firefox Linux 99.0), but does work in Chrome and Firefox on my mobile, so closing the issue

**Comment by dartcafe** [comment]
Disable your adblocker.

**Comment by jandr** [comment]
Thank you @dartcafe, it was uBlock origin's fault, despite everything seemingly being allowed, the domain of the Nextcloud instance set as fully trusted, and nothing showing as being blocked... but it was. 

Sorry for not checking *disabling* uBlock completely before raising the issue (and not double-checking from the mobile as I did after raising it... seeing it worked there was the reason I closed the issue assuming it was my browser's fault somehow...)

Thanks for the tip!

**Comment by B14CK313** [comment]
Sorry for commenting on this closed issue, I found it while searching for a solution to the same problem and wanted to add a better solution for anyone also having it:

Instead of completely disabling uBlock Origin, you could/should create an exception for the specific filter (until this gets fixed in the filter list):
The filter rule causing this issue is from the Fanboy’s Annoyance filter list: `##.sidebar-share`.
To create an exception for this rule navigate to uBlocks settings, click on the 'My filters' tab and add
`affected.domain#@#.sidebar-share` (replace `affected.domain` with the domain of your Nextcloud instance)
This way you can leave uBlock enabled.

I hope this helps anyone also having this problem and searching for a solution!
