### ISSUE TITLE
Omit the "Enter name and email address" dialogue if name and email address are known

### ISSUE THREAD

**Issue by PhrozenByte** [nextcloud/polls#2399]
## Describe the goal you'd like to achieve

As a poll owner, I don't want that poll participants have to use the "Enter name and email address" dialogue if I already provided this information (see #2367; if participants were invited by email address only, we still need the dialogue). The reason is that users often fail to provide this information properly.

## Describe possible solutions

Since the information is already known, the "Enter name and email address" dialogue serves no real purpose and might confuse users, thus it should never been shown by default.

Even though I don't share @dartcafe's privacy concerns (see https://github.com/nextcloud/polls/issues/2367#issuecomment-1104523371; the poll owner already has this info, so how could this be a privacy issue?), there might still be other reasons for participants to change their name or email address. Thus I'd suggest adding a button to the voting page to bring this dialogue up at any later point. This would also benefit any other poll participant if they somehow failed to provide this info properly at first.

**Comment by dartcafe** [comment]
I totally understand the issue, but I want to get into the arguments a little bit deeper. 

> The reason is that users often fail to provide this information properly.

Although I agree to this, I doubt if any problem can be solved by user patronization. The provided informations are prefilled and I judge a user's right of self determined privacy higher than a possible confusion. Especially because the only effort a user has to take is reading and clicking. 

> the "Enter name and email address" dialogue serves no real purpose

It has the purpose to let the user decide, how his information should be presented.

> the poll owner already has this info, so how could this be a privacy issue

I didn't say privacy **issue**, I said there could be privacy **concerns**. See above and the fact, that the name of the user is not only presented to the poll owner, but also to all participants. And possibly the prefilled name entered by using the email information from an addressbook is not the usually used name of the user or simply is wrong (spelled).

> Thus I'd suggest adding a button to the voting page to bring this dialogue up at any later point

This would be bad UX and a possible GDPR conflict, because you force the user to present his information without any choice and skip agreeing to the privacy terms. And then you rely on him finding the button for changing the data. 

I bet, if we would implement the suggested changes, you will will have immediate requests for reverting this out of different opinions and arguments. 

Nevertheless this will take time and effort to realize and test the implementation by achieving a very limited value but creating additional risks.

All over all, I think the current implemenation is a better one. 

So sorry for a 👎 for this request.

**Comment by PhrozenByte** [comment]
> Especially because the only effort a user has to take is reading and clicking.

To put it with an idiom: "Sounds great, but doesn't work."

We run polls with sometimes >100 participants per poll and surely a few thousand in total in the last couple of years, so I can tell you for sure that the majority of users don't read. We did polls with university students, we did polls with CEOs of large companies, and everything in between. Most of them don't read modals :unamused: Why don't they read modals? I don't know, maybe because they are familiar with clicking away any modal due to cookie banners and stuff?

We wasted hours fixing this by manually collating the participants list with the votes. Even though this shouldn't be necessary at all, it is sometimes rather easy at least - purely because the email address matches. But sometimes we have to manually go through the list to find the participant. You can imagine how much fun this is... We learned the hard way...

> Nevertheless this will take time and effort to realize and test the implementation by achieving a very limited value but creating additional risks.
> 
> All over all, I think the current implemenation is a better one.

I sporadically follow your repo and in my perception the modal rather is a constant source of issues :thinking: I remember a quite large number of issues about removing the modal, some because users fail to provide the info, at least one about users trying to log-in with their organization's credentials (I remember this specifically because it was kinda amusing :smile:), and a few about various similar, but rather small issues. 

I see your intention, but I'm afraid that the modal just doesn't work the way you intend it to work :disappointed: 

**Alternative solution:** Even though I still believe that proactively asking the user about his name and email address isn't really necessary if we already have this info, I'm more concerned about the UX. A modal popping up when navigating to a website is perceived badly by the user - not because of the contents of your modal, but because people are familiar with annoying modals asking for cookie preferences and stuff. Thus it should be redesigned not be a modal.

I remember that you already have an issue about this, so I'm asking for making this existing issue one of the top priorities.

> This would be bad UX and a possible GDPR conflict, because you force the user to present his information without any choice and skip agreeing to the privacy terms. And then you rely on him finding the button for changing the data.

I disagree.

One doesn't create polls for fun, but for a reason. Name and email address are necessary information to participate in the poll. Thus processing this information is fine in accordance to Art. 6 I lit. b GDPR. You don't need permission for this.

This is quite important! The data processing doesn't rely on the user's permission (Art. 6 I lit. a GDPR), but on the necessity of the processing (Art. 6 I lit. b GDPR). You can't ever rely on the user's permission for this, because inviting any user except for public links and registered users would then be a GDPR violation. For the GDPR it doesn't matter whether the data (name and email address of invitees) is shown somewhere, the pure existence of this data would be a GDPR violation from the moment the poll owner enters the data.

I can't really comprehend with the "without any choice" statement, because neither is any information shown until the user actually participates, nor is the user forced to use the provided values since the user can still change the values :confused: 

**Alternative solution:** I'm fully aware that redesigning the modal is quite a lot of work to do (see above), thus I suggest adding a config setting (`occ config:app:set --value=0|1 polls show_registration_modal` - i.e. not even in the app settings) in the meantime, so that the admin can choose what to do. The modal is quite controversial, thus giving the power to the admin is the right thing to do.
