### ISSUE TITLE
Offset for footer is missing

### ISSUE THREAD

**Issue by xf-** [nextcloud/polls#2681]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

Can see all options on mobile. Last one is behind the footer.

### What did you expect, how polls should behave instead?

Add offset for the footer.

### What steps does it need to replay this bug?

1. create a poll
2. use the share link on mobile
3. last option is behind the footer (set a slogan or name...)

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a much older version (more than one major version)

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [X] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Which System did you use, when experiencing the bug?

- [ ] Windows
- [X] Linux
- [ ] MacOs
- [ ] iOS
- [X] Android
- [ ] Other/Don't know

### NC version

Nextcloud 25 (Nextcloud Hub 3)

### PHP engine version

PHP 8.1

### Database engine

MariaDB

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Additional Information

Using the latest beta (had the issue also on 4.0)

**Comment by dartcafe** [comment]
This comes from Nextcloud's base template. I removed the footer.

**Comment by xf-** [comment]
I would prefer a solution with the footer. Share link allows people to enter an e-mail and Nextcloud supports Privacy Policy and Impress link. Could be necessary in some use-cases.

**Comment by dartcafe** [comment]
@xf- The footer is obsolete for that since the privacy policy and legal notice are provided within the registration form. This is neccessary, because the user has to be informed about them **before** he provides his personal data and he has to agree to the privacy policy. 

![grafik](https://user-images.githubusercontent.com/26707476/204733784-0f4588ce-0c41-4654-80bb-195e40fa15c7.png)

For Polls individual terms can be used via the administrative settings. If none are set, the default terms are used.

![grafik](https://user-images.githubusercontent.com/26707476/204734339-c3f2c8aa-f929-49af-a0d7-76534b0e033f.png)
