### ISSUE TITLE
Enhancement / Usability Suggestions

### ISSUE THREAD

**Issue by NotReallyNotNotMe** [nextcloud/polls#2689]
### Your Message to the world

My comments are meant to help make the app more user friendly.

    Adding time for a date - roll downs are tedious to use. Provide a box to type in time and date without having to play with rolling selection.
    Very hard to add a new date. I click on the calendar/plus option, nothing happened.
    Sharing - make it so one can select multiple attendees from the contact list rather than having to type in each name, and then clicking on Send invitation mail. Too many key strokes. One should be able to mail to all at once using a pick list from contacts. Make it so send goes to all. Yes, I know one can select a group but that does not apply when the share list varies.
    If a date is entered by mistake, hard to find how to delete that entry. Provide a delete button.
    Have a delete option for a poll rather than needed to archive, delete, etc. Or, at least make it an option on the three-dot menu drop down. (Yes, I have seen the counter argument. Make it user friendly.)

Thanks for the efforts.
/Roger

**Comment by dartcafe** [comment]
Hi @NotReallyNotNotMe Thanks for your suggestions. But please: 
1. Allow a single issue for each request and
2. use the [appropriate form](https://github.com/nextcloud/polls/issues/new?assignees=&labels=enhancement&template=FEATURE_REQUEST.yml) .

Issues with multiple requests can't be solved and tracked. And rather in thinking in solutions, please try to think in the goals you want to achieve, so I can better understand what the real problem is. This is why requests should be formed as a user story. 

Of course possible solutions can be applicated, too.

**Comment by NotReallyNotNotMe** [comment]
What don't you understand?

-- Roger Broseus
Typos? Typoes happen.

-----Original Message-----

**Comment by dartcafe** [comment]
It is not about understanding. It is about:


> * Allow a single issue for each request and
> 
> * use the [appropriate form](https://github.com/nextcloud/polls/issues/new?assignees=&labels=enhancement&template=FEATURE_REQUEST.yml) .

And about not requesting a solution but describing yout goal or your problem. See the feature request form, you will find the explanation there.
