### ISSUE TITLE
Consolidate poll types and add location field

### ISSUE THREAD

**Issue by martingwb** [nextcloud/polls#2854]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

As a poll owner, I want to be able to do date polls where for each option context or location can be added, because it helps the participants to make a choice e.g. you can choose between 2 different location for the same date. The text field would allow to give further context for each option.

### Describe possible solutions

Each field (date/time, text, location) should be configurable for each option.
That would allow consolidating the poll types by not differentiating between date poll and text poll.

**Comment by dartcafe** [comment]
Any proposal, how the dialog for adding an option and the presentation of the vote page could be designed?

**Comment by martingwb** [comment]
- Rename the "Add a date" button to "Add an option"
- Only one of the fields date/time, text, location need to be used, the other two are optional
- Offer to select if a date/time will be used of not - if yes, same as now, if no, text field or location field need to be used
- Offer a text field
- Offer a location field
- Only the use fields need to be displayed in the vote page

**Comment by dartcafe** [comment]
Yes thanks, I was asking for a visual proposal, since it is a UX challange.

**Comment by martingwb** [comment]
Something like this maybe?
![draft](https://github.com/nextcloud/polls/assets/13892083/bd4fa455-8ba7-47c4-8563-2b053f865f56)

**Comment by dartcafe** [comment]
Ah. OK. (Besides the fact, that my eyes hurt from the colors 😉)

So you want to add a new text field on top of the date picker. 
Some additional questions: 
* How long may the text be? 
* How does it look, if you have, let's say 12 date options?
* Is the location option skipped by intention?
* What is the date switch for? Is it meant to add a text instead of a date?
  * In this case, how would a vote page look with 6 date and 6 text options?
  * How should they be sorted? First the options without date, then the options with a date?

**Comment by martingwb** [comment]
>Ah. OK. (Besides the fact, that my eyes hurt from the colors wink)
     Well, you asked for it :-)
>So you want to add a new text field on top of the date picker.
     Yes, but an option can also consist only of the text field (by that it would cover a date poll as well as a text poll of the current version).
>Some additional questions:
> How long may the text be?
     I would suggest 35 characters
> How does it look, if you have, let's say 12 date options?
     Same as it is now. If there also is a text field it will be split into 2 or 3 lines. If the window get too small a scroll bar will be displayed.
> Is the location option skipped by intention?
    Yes, as I mentioned before, having a text field would be enough and it can be used for context and/or location. A specific location field would need to add some more functionality (e.g. link to a map). 
> What is the date switch for? Is it meant to add a text instead of a date?
     Date switch is for not using a date. In case there is no content in the text field the date switch would be "on" by default. The idea is that you need to use either text or date and using both is also possible within one option. Also options with the same date/time need to be possible as they can have different text (i.e. location, context, etc.)!
>        In this case, how would a vote page look with 6 date and 6 text options?
     see screenshot
> How should they be sorted? First the options without date, then the options with a date?
     Same as the text poll options are currently handled - by drag-and-drop
> Edit: A proposal for the mobile/list view would also be nice.
     see screenshot
![draft2](https://github.com/nextcloud/polls/assets/13892083/7244aa2e-db31-4ee0-94f8-2e661a5e5c7a)
![draft4](https://github.com/nextcloud/polls/assets/13892083/6d5fa799-5570-45fb-bd39-bdef9d19d0ab)

**Comment by dartcafe** [comment]
> > Ah. OK. (Besides the fact, that my eyes hurt from the colors wink)
>
> Well, you asked for it :-)

Thanks 😉 My doc says, everthing will be good after a while. 😄 

> > So you want to add a new text field on top of the date picker.
> 
> Yes, but an option can also consist only of the text field (by that it would cover a date poll as well as a text poll of the current version).

OK, got it.

> > Some additional questions:
> > How long may the text be?
> 
> I would suggest 35 characters

Why not 70? I know, it is provocant, but you can count the seconds until users request more space. 
 
> > How does it look, if you have, let's say 12 date options?
> 
> Same as it is now. If there also is a text field it will be split into 2 or 3 lines. If the window get too small a scroll bar will be displayed.

I fear mixed poll with tests and dates could get be very fluttery. Also text options need a greater width, otherwise words need to be wrapped too often (in some languages more than once; think a bout german words)

> > Is the location option skipped by intention?
> 
> Yes, as I mentioned before, having a text field would be enough and it can be used for context and/or location. A specific location field would need to add some more functionality (e.g. link to a map).

OK, got it. So we understand the location or what ever will be entered in the textfield as an information. BTW: An address can easily extend 35 characters.

> 
> > What is the date switch for? Is it meant to add a text instead of a date?
> 
> Date switch is for not using a date. In case there is no content in the text field the date switch would be "on" by default. The idea is that you need to use either text or date and using both is also possible within one option. Also options with the same date/time need to be possible as they can have different text (i.e. location, context, etc.)!

Ah, it is used to disable the date selection.

> > In this case, how would a vote page look with 6 date and 6 text options?
> see screenshot

Yes, but for a couple of informations you need more structure, like an address for example. (Referring to variable width)

> > How should they be sorted? First the options without date, then the options with a date?
> 
> Same as the text poll options are currently handled - by drag-and-drop

Date options are always in date order and are not draggable. In this way, there is no chance to tell, which text option has to stay at which position. Before or after which date option. Adding or removing a new option can influence the order as well. I have no idea how code that relyable.

> > Edit: A proposal for the mobile/list view would also be nice.
> 
> see screenshot ![draft2](https://user-images.githubusercontent.com/13892083/238560980-7244aa2e-db31-4ee0-94f8-2e661a5e5c7a.png) ![draft4](https://user-images.githubusercontent.com/13892083/238561004-6d5fa799-5570-45fb-bd39-bdef9d19d0ab.png)

Shouldn't date options stay in one column for better readybility?

Thank you for your proposals and suggestions, that is what good development is about. It is good that people here take part in a serious discussion about the feature development. 

Buuuut. All in all, i see a lot of caveats, which will result in a huge amount of work. There will be a lot more combinations of options which will be really hard to maintain. The complexity will raise for the development and for the users.

In the end the question is, how many users really need this and which value would it create? The description field is a good place for additional information and explanations. 

Because of this, I fear this feature request has a very low to no chance to get realized. But I am still open for suggestions.

But there is another issue, which requests to combine polls as a group. Maybe this could be a solution to combine text and date polls.

**Comment by dartcafe** [comment]
@martingwb Comming back to this proposal after a while thinking about it. 

Thanks for the effort in explaining and drilling down your request. But I am sure, this will not be developed. Mixed polls are out of scope of this app and have a lot of caveats when it comes to the ux design:
* sorting
* aligning
* editing the options
* etc. 

Too much work for an edge case. So I will close it.
