### ISSUE TITLE
[Feature Request] Email address should be required for anonymous votes

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/polls#286]
I think it should be possible to vote for people which do not have Nextcloud account, like doodle allows it.
If the admin allow anonym user to add his vote, he should be able to set up an E-Mail address as a required field.

**Comment by splitt3r** [comment]
Anonymous voting is already possible but you only habe to enger your name. But an email address could also be fake.

**Comment by Mannshoch** [comment]
The thing is that If a User do not have a Nextcloud Account and would Like to participate a Vote he should has the Opinion or, what I wish, has required to add an E- Mail address.
I do not wish to use this tool for People I do not know but for People which do not have an account. 
I need the Mail address for further planing.

**Comment by ccoenen** [comment]
If this is added, please make it an option.

**Comment by JoergAW** [comment]
Optimal solution:  send to a list of emails for voting.  Each recipient gets a URL-enclosed token for ONE-vote (can be edited not duplicated).  As a poll option the voter (1) may, or (2) may not choose to enter a visible name or (3) the email is visible or it is (4) anoym.  The admin may see the email-assignment anyway   (enjoyed at https://www.konsensieren.eu)

**Comment by Mannshoch** [comment]
See also my enhancement request: https://github.com/nextcloud/polls/issues/552

**Comment by kainhofer** [comment]
I'm in a similar situation, but JoergAW's suggestion (send individual invitiations to an explicit list of emails) does not work for me. I'm arranging meeting of a professional working group, which have a dedicated mailing list. I don't even have the full list of members, I'm just organizing. So I set up the poll and send the link to the mailing list. When the poll is finished, I'd like to invite all members that voted yes/maybe for the selected date.
Only problem is: I don't have their addresses... All I can do is send the invitation to the whole mailing list...

I also agree that an e-mail address should not be mandatory by default, but it is useful for some use cases.

**Comment by nextgen-networks** [comment]
Have an option to vote without a user account would be fantastic.

But instead of having precreated token it would be more comfortable to have a 2/3 step verification process.
Step 1: user adds a temporary vote, to validate his vote he needs a e-mail
Step 2: a opt-in verification mail is send to the user and he has to validate his vote - nice side effect: your poll is GDPR compliant ;-)

optional step:
a) poll-admin creates a predefined list of mail adresses or domains that are able to vote
b) poll-admin validates each vote after the opt-in verification (maybe as daily digest to lower the amount of mails

@dartcafe would be fantastic to read your opinion about e-mails for anonymus voters

Thanks for your hard work on this app!

**Comment by dartcafe** [comment]
An anonymous poll is GDPR complaint by default. because it is anonymous. Adding mail addesses for verification need a verification process, which is an asynchronous and rather complex process. 

Managing temporary votes is also rather complex. 

All sounds as a heavy invest for a limited value.

What is on the to do list is an invitaion system, so you can prediefine, which user (internal and external) can participate in the poll. A token will grant editing the own vote until the expiration of the poll. 

Also a public user will be able to enter a mail address for notification. Maybe, we can make this as a required information.

**Comment by CATER-COM** [comment]
+1 
Would be great this way the attendees could be notified about the result :)
