### ISSUE TITLE
Make Title visible before/while entering your Name on mobile devices

### ISSUE THREAD

**Issue by KaeTuuN** [nextcloud/polls#3146]
### ⚠️ This issue respects the following points: ⚠️

- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Describe the goal you'd like to achieve

As a poll participant, I want to see the Title of the Poll before/while entering my name, because it helps to get all necessary Information.

Example: If I get a link to a Poll on Threema or Signal and click on it, I can't see the Poll Name without entering a my Name.

### Describe possible solutions

a) Just write the Poll Title above "Guest Account" 

b) Don't make the Popup Fullscreen so the Title "behind" is visible.

### Additional context

![NC_Poll](https://github.com/nextcloud/polls/assets/10331843/10462336-8a96-4307-ae8c-c526fdd7c001)

**Comment by dartcafe** [comment]
You should not see the dialog when entering a public link since version 5.4.x anymore. The dialog doesn't raise anymore upon entering, but the user gets a request to register to this poll to participate.

The "Register"-Button needs to be fixed to identity it as a button. Will get fixed soon.

![grafik](https://github.com/nextcloud/polls/assets/26707476/668eaed1-119b-47ad-b863-1a23ffaff1dc)

**Comment by KaeTuuN** [comment]
Ouch... Forgot to check for App Updates...
Updated from 5.3.2 to 5.4.1 and everything is fine. Thanks for pointing me to the right direction!
