### ISSUE TITLE
[Feature Request] Radio button option instead of all tertiary choices

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/polls#319]
I like this app, and the tertiary choice button of yes/no/[not sure](https://www.youtube.com/watch?v=sVyRkl5qNb8) is pleasantly novel. I'm new here so "up from the mouths of babe's"?

I hope that in the future there will be options for the available choices. Vending machines don't let you pick 2 yes, 3 no, and 4 maybe's. A poll where users are forced to select one from a list is so standard that I think it should get priority, but some polls are about ranking things, others are about fuzzy logic like satisfaction surveys. Top three choices of a long list of options is popular for many things like dream-sheets for where an employee wants to transfer to.

This is a very cool app, but I can't see using it for much if every poll has all options selectable on every poll. What if a person picked everything as maybe on a meeting date option list? That's a useless response to a poll, we knew maybe before asking them.

**Comment by dartcafe** [comment]
I am not sure if I get you right. What I believe I understood is, that you want more option to support surverys. I.e. that you can ask, "how was a meal, rank it from 1 to 10"?

Or to have a choice to give more and free selectable than the three answering options?

**Comment by WNYmathGuy** [comment]
Yes @dartcafe you understood my commentary. Web forms have often had option types for questions like: 
- radio-buttons where a user can only select one of many options
- check-boxes where a user can select any number of options from none to all options.
- sliders where a user moves a widget like a volume control to indicate a level of satisfaction
- text entry for numerical values, phone ID's, words, hand typed dates, and so on

I'm certain that there are other unique ways to accept an answer to a question in a survey, but the ones I named above are some popular ones to add to your tertiary method.

**Comment by dartcafe** [comment]
I see your point, but I fear this goes behind the scope of this app. The intention is to have a simple poll app, where you can easily coordinate meetings or other dates with more than two people. Additionally the text poll is an addon for quick polls. We are now at a pont, where we can manage the lyout, because elements are restricted in their apperance. Variable bunches of checkpoxes, pull downs, radio buttons and text fields will make it harder to get an acceptable UX. 

And developing and testing will get a hell. Let`s follow the MVP principles...
