### ISSUE TITLE
Exception json_decode(): Argument #1 ($json) must be of type string, null given in file '.../apps/polls/lib/Db/Preferences.php' line 71

### ISSUE THREAD

**Issue by kinimodmeyer** [nextcloud/polls#3216]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

I get the above error when i want to access the polls since the upgrade to nextcloud 28.0.0.
I added a (string) cast in in .../apps/polls/lib/Db/Preferences.php::getPreferences_decoded to make it work but do you have any idea why "$this->getPreferences()" returning "null"?  The column "preferences" in table oc_polls_preferences is NULL in many rows, is it because of that?

### What did you expect, how polls should behave instead?

Not php error crashing the site

### What steps does it need to replay this bug?

unclear

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from previous major version (i.e. 3.x.x to 4.x.x)

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### NC version

Other/Don't know

### Other Nextcloud version

Nextcloud 28.0.0

### PHP engine version

PHP 8.0

### Database engine

MariaDB

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
Yes. I assume this is the reason. 
But would be good, if you fill out some more information, since it helps investigation. 

At least the error trace.

**Comment by addy90** [comment]
On Nextcloud 28.0.3 with Polls 7.0.0 on PHP 8.2, the issue is back.
`Exception
json_decode(): Argument #1 ($json) must be of type string, null given in file '/var/www/nextcloud/apps/polls/lib/Db/Preferences.php' line 73` (now in line 73 instead of 71)
The current version of the file polls/Db/Preferences.php shows that the fix from #3219 is not there anymore: https://github.com/nextcloud/polls/blob/07ea799cd9e413ebb4bbd73789af8756603abdc0/lib/Db/Preferences.php#L73
The issue was reintroduces three weeks ago: https://github.com/nextcloud/polls/commit/1cfae8044d9e2ed2a6a1d488a322a23b97896c09#diff-bc5df2db532ee41b7336a0f621e526a3c85fb378c26735eba0ab6998c5c25d0c

Thanks for your support and hard work!
