### ISSUE TITLE
Feature request: Vote whole day

### ISSUE THREAD

**Issue by dekuenstle** [nextcloud/polls#33]
It would be nice, if you could vote for the whole day e.g. by clicking on the timeline.

**Comment by Juliku** [comment]
I'd like to expand this feature request to timespan. For example to be able to set a whole day or more consecutive days to be voted. Thanks

**Comment by dartcafe** [comment]
That‘s a little bit complicated, because a user has to choose, which timespan he wants to vote for and then he has to decide, which status he wants to change to. Making this intuitive is not easy, and the benefit is limited. 

At least it is a lot of testing for every release. I vote for not implementing this and close this issue.
