### ISSUE TITLE
date picker shifted

### ISSUE THREAD

**Issue by dercaptainbc** [nextcloud/polls#3705]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

We have found this small but annoying bug. The problem is, I'm pretty sure it's caused by using the custom side menu app, because it shifts everything 40-50px to the right.  Do you see a quick way to solve the problem?
![Screenshot_Umfragen_verrutschte-Box](https://github.com/user-attachments/assets/87a7f5d9-ce2a-496c-83a8-58bdf9e6db49)

### What did you expect, how polls should behave instead?

the date picker should not be shifted, as you can only use it in a limited way

### What steps does it need to replay this bug?

1. Install Custom Menu 
2. Mode show always
3. Try to add some Dates to the Poll

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Affected polls version

7.2.0

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [X] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### NC version

Nextcloud 28

### PHP engine version

PHP 8.2

### Database engine

MariaDB

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

**Comment by dartcafe** [comment]
Sorry, this no bug which is caused by Polls itself and is not solvable here. 

The picker is a component from the [nextcloud-vue components](https://github.com/nextcloud-libraries/nextcloud-vue) and its position is calculated inside the component. I would rather see the issue caused by the Custom Menu, since I guess it changes the offset for the position calculation.

I guess you should rather open an issue in the repo of Custom Menu.
