### ISSUE TITLE
[0.9 beta 4] Please help testing. 

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/polls#383]
0.9 beta 4 is out: https://github.com/nextcloud/polls/releases/tag/v0.9-b4

Please help testing.

**Comment by joergmschulz** [comment]
NC13: the create-poll screen is completely empty on Chrome and FF. 
some relevant console messages (browser console):

```
TypeError: "OC.getLanguage is not a function"
TypeError: "this.poll is undefined"
```
can I do something to find out more?

**Comment by dartcafe** [comment]
OK. I will change min version to NC14.

**Comment by BurtGummer** [comment]
First: great work!

i have update my Nextcloud to 14, then i install this polls-version. but i can not change a existing poll:

![image](https://user-images.githubusercontent.com/1249295/45943942-af598e80-bfe8-11e8-9137-87261830843d.png)

Because the window from the calendar is not visible on long polls (the black part of the Screenshot is my Windows-Taskbar). In a new poll, i see the calendar-window.

On a new poll, there are many english words, for example:

![image](https://user-images.githubusercontent.com/1249295/45944177-7ec62480-bfe9-11e8-85ad-0f4d2e0fd248.png)

**Comment by dartcafe** [comment]
Yes. Good idea. I will optimize that after the next release, when I change the votes page to vue too.

**Comment by herrmannsdorfer** [comment]
Adding to BurtGummer's scroll issue: The settings icon/link is also off screen when there are many dates. You have to scroll to the right to see the icon and open the sidebar to see the comments etc. It would be more accessible to pin the icon to right border of the browser window.

**Comment by dartcafe** [comment]
Both done in current stable-0.9 branch

**Comment by natrius** [comment]
Hope it will get released soon. Is there an estimation?

**Comment by dartcafe** [comment]
Not a real ETA, but soon. We are preparing the release and awaiting it this month.

**Comment by dartcafe** [comment]
Thanks for all support!
