### ISSUE TITLE
Give access and send to spécific not registred user

### ISSUE THREAD

**Issue by CATERBN** [nextcloud/polls#388]
Actualy the select access option only permit to select registred users or groups.

It could be nice to select invited people from the Contacts app and optionnaly using Contacts group. Option 1 : the poll (title + description + emphased expiration date + link) is send to invited by mail.
Option 2 : the invited should "authenticate light" by providing there email adress
Option 3 : after closing poll sending result and/or message to invited peoples

**Comment by dartcafe** [comment]
Thanks. This is on the to do list.

**Comment by JoergAW** [comment]
Optimal solution:  send to a list of emails for voting.  Each recipient gets a URL-enclosed token for ONE-vote (can be edited not duplicated).  As a poll option the voter (1) may, or (2) may not choose to enter a visible name or (3) the email is visible or it is (4) anoym.  The admin may see the email-assignment anyway   (enjoyed at https://www.konsensieren.eu)

**Comment by dartcafe** [comment]
From 1.0:
- Invite site users to hidden polls
- Users of a public linked poll get a personal link before they can vote. With this link, reentering the poll ist possible.

**Comment by CATER-COM** [comment]
Hi it's really a great job +100 :)

But il seem that the link shared by mail doesn't work. The link bring user to a page message "Polls doesn't exist". It seem that it create a spécific public link (nice because I suppose this case the user don't need to register, it use the adressbook name). But the link created isn't linked to the poll.

If the bug below is solved, do you think it could be possible to use not only nextcloud user group, but also contact app group. This way you can send your poll to a large group of contact without chekin each one by one in the dropdown list. Search box is looking in the group field but it doesn't provide a way to click on group name to select the whole contacts tha belong to it.

Thanks for all of this job !
