### ISSUE TITLE
[Feature Request] Remove / modify vote from an anonymous user

### ISSUE THREAD

**Issue by RalfAlbers** [nextcloud/polls#397]
The owner of an public poll should be able to remove or modify the vote from an anonymous user.

**Comment by t-gerhard** [comment]
I have the same use case as @japso - a public poll with many anonymous users over one or more months times (for scheduling a movie-watching group). I use my private nextcloud where most participant's do not have accounts. Since it sometimes take two weeks for scheduling, and participants find other appointments as well, it happens that participants need to update their info. I don't want to force every participant to create yet-another account.

As a first step, poll creators should be able to edit entries of anonymous users. I also don't see a reason why a poll creator should not be able to edit any entry (as polls is a tool for finding consensus), which should make implementation easier.

As a second step, I would suggest using a cookie-based solution, as doodle.com has - i.e., adding an entry as anonymous user creates a cookie that authenticates the user as authorized to edit/remove the own entry.

**Comment by rubo77** [comment]
Any progress? This is essential!

**Comment by dartcafe** [comment]
Not yet. Migration of the votes page is the first step. The main page ich nearly ready.

**Comment by olgru** [comment]
Just to put a stake here...
This features is really wished. I use poll as I don't want people to use doodle... But then I got emails like "on that date I can not" or "can you please allow me to revote"? Than I have 2 or more lines from the same person (at least the same name) and as a result the summary values doesn't fit anylonger.
As poll owner I want to: edit individual votes (maybe with a comment "value changed by poll owner") and also I want to remove vote lines...
This request is open since January. I put my comment here just to emphasize that this feature is wished by me too..
But to be clear: I really appreciate all the work in this system and I'm showing these beautiful solution wherever I can. Great job, everybody!

**Comment by dartcafe** [comment]
This is the problem of doing such things in the free time and things have to be done before. Sorry. I just reentered development. Had noc time in the last months. Sorry, job and health goes first.

**Comment by olgru** [comment]
My personal view? Health first ... family first ... both is more than any job... Thanks for all the work and thanks for your response.

**Comment by dartcafe** [comment]
Poll owners and Admins are able to edit votes of public and invited users as a first step via using personal links of these particitipants from 1.0 on.

**Comment by natrius** [comment]
That is awesome to hear! Maybe later it is possible to implement a cookie-based solution like https://github.com/nextcloud/polls/issues/397#issuecomment-451888376 mentioned here. 

Thanks for your amazing work in your freetime! :)

**Comment by dartcafe** [comment]
#736
