### ISSUE TITLE
Creator of poll should NOT automaticly added as attendee 

### ISSUE THREAD

**Issue by frank-github** [nextcloud/polls#556]
Poll 0.10.2

Creator of poll automaticly added as attendee and all poll options had count 1 for not possible.

I want to create polls, but my account should NOT be part of this poll !

**Comment by dartcafe** [comment]
I don't understand this. The owner is not automatically a participant for now. Or do I miss something.

**Comment by kainhofer** [comment]
I think the issue here is mainly that the counts shown for each choice already include your entries (i.e. the entry of the current user viewing the page), even before you press "vote". So when you create a poll and view it as the owner, you will appear in the list of participants with all options deselected, so all options already show 0 YES and 1 NO vote for each option:
![image](https://user-images.githubusercontent.com/4689419/56462555-5490e580-63c5-11e9-823a-1a5a5492d93a.png)

This gives the impression that the owner is automatically added as a participant with "NO" set for all choices. Other users won't see this, though.

Shouldn't there be some kind of visual distinction between the current user having already voted and the current user before actually casting a vote?

**Comment by frank-github** [comment]
Yes, this describes my problem.

**Comment by dartcafe** [comment]
Ay. This occures, because, when you enter the poll all votes are set to no as long you did not opt in for an option. This is a wanted behavior. You are not part of the poll unless you did not send your vote.
