### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by frankm42** [nextcloud/polls#580]
### What is going wrong?

The user interface as it is now (v. 0.10.2) has several areas that seem confusing to general users.

A) Default to negative reply:
When a user opens the poll (and has not yet voted) the default reply of that user is already set to negative. This is very confusing as it looks like there is already a negative reply for all dates.

**Expected behavior**
There should not be any choice preset before the user has actually entered something.

B) The comment section can be mistaken for a login field:
Even with only a handful users, I have had several cases where users have entered their password into the comment field, because they mistook it for the login form. As this comment cannot be edited again, this is quite a problem. 
In organisations with > 5 users, this will rather be a daily occurance I'd assume. 

**Expected behavior**
Simplest solution could be to make the comment field larger to make it obvious it is a text field.

C) There is no login field:
I have had (angry) users tell me they couldn't find the login field when they accessed the poll through a link.

**Expected behavior**
Adding a link to the login page with a jump back action to the poll after login would solve this.

**Comment by dartcafe** [comment]
To A) The default is a opt out, so this is wanted behavior. BUT: a user cannot tell, if he has already voted, if all is set to unvoted. So there should be an edit option to change the vote. 

To B) Good point, we should overthink that. There should also be a synchronisation between the user names. 

To C) You mean, when the poll is not a public one? 

Generally: Could you open separate issues, so it is easier to plan the development. My time is very limited at the moment due to another project, which I earn money with. I will resume to development mode soon.

**Comment by frankm42** [comment]
Opened seperate Issues
