### ISSUE TITLE
Provide displayNames instead of userId

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/polls#715]
#402 is back.

![Bildschirmfoto 2020-01-08 um 13 42 17](https://user-images.githubusercontent.com/43957716/71979074-1a9a9480-321d-11ea-922d-3842a3d7f966.png)

**Comment by herrmannsdorfer** [comment]
Looking at the screenshot I would also take care of the column width (created entries overlapping expiration date) and the vertical alignment of the owner to the other text lines.

**Comment by dartcafe** [comment]
I have to fiddle out, how to get the displaynames via the js API. comes later.

**Comment by tortuetorche** [comment]
Hi @dartcafe,

First of all, thank you for this great Nextcloud App 👍 

Here some clues to display names instead of user id, based on [Nextcloud Talk/Spreed](https://github.com/nextcloud/spreed) code :
Nextcloud Talk use the [`@nextcloud/auth`](https://github.com/nextcloud/nextcloud-auth) NPM module, here the reference: https://github.com/nextcloud/spreed/blob/v8.0.0/package.json#L18

Then, here the code to load this module: https://github.com/nextcloud/spreed/blob/v8.0.0/src/PublicShareAuthSidebar.vue#L37

Here the code to manipulate the `getCurrentUser()` object: https://github.com/nextcloud/spreed/blob/v8.0.0/src/PublicShareAuthSidebar.vue#L164

And finally, the code to extract the `displayName` of the user, if any: https://github.com/nextcloud/spreed/blob/v8.0.0/src/store/actorStore.js#L135

Have a good day,
Tortue Torche

**Comment by tortuetorche** [comment]
Hi folks,

I think my [previous comment](https://github.com/nextcloud/polls/issues/715#issuecomment-578190370) go in the wrong direction, because it's only focused on the current user 😕 

Cheers,
Tortue Torche

**Comment by dartcafe** [comment]
Yes, right. The displayNames are AFAIK not available via the JS API. But I want to avoid loading every username via a individual API-Call. That means, I have to load them when gathering the information in the backend. This means extending the models. I need some time for that. Stabilizing the app has a higher priority ATM.

**Comment by Dennis1993** [comment]
I have the same problem, I don’t know who has voted 😅🤷‍♂️
NC 17.0.2 on Ubuntu with Polls 1.1.6

**Comment by dartcafe** [comment]
See beta4 in the releases. There are some more enhancements and fixes. please report bugs in new issues.

**Comment by herrmannsdorfer** [comment]
Resolved in 1.2.0b4. Good job!
