### ISSUE TITLE
Friendly URL

### ISSUE THREAD

**Issue by Geonov** [nextcloud/polls#850]
The poll's public link (like xxxx/index.php/apps/polls/s/94Khjla2ATIjiOTA) is not user friendly.

I would like an option to rename it, like : 
xxxx/index.php/apps/polls/s/my-fantastic-poll

Something like ShareRenamer (https://github.com/DecaTec/sharerenamer) for files sharing.

**Comment by dartcafe** [comment]
I am not sure, if this is a good idea. The share token is a secret and unique. 

When a user defines a user friendly token we have to check, if it is unique. By adding the possibility to define own tokens, we make it possible to guess other user's shares.

**Comment by cptMikky** [comment]
@dartcafe I would like to have this feature, too, so to address some of your concerns:

> The share token is a secret and unique. (...) we make it possible to guess other user's shares.

It is imho for the poll owner to decide whether this is an issue or not.

> we have to check, if it is unique. 

This check should be performed regardless of the token source.

**Comment by dartcafe** [comment]
> It is imho for the poll owner to decide whether this is an issue or not.

No it is not, because it will reveal another user's share name, if there will be a duplicate error.

**Comment by cptMikky** [comment]
> > It is imho for the poll owner to decide whether this is an issue or not
> 
> No it is not, because it will reveal another user's share name, if there will be a duplicate error.

That still may not be an issue. The "revealed" poll's owner probably used a nice name because they _wanted_ the poll to be publicly accessible - same as with web domains. If someone wants the poll to be hidden, it is very unlikely they'll use an easily guessable link in the first place. I stand by my opinion that if someone use a "guessable" share, it is because they want the share to be public and if someone else "accidentally" stumbles upon such a share, it won't present an issue for the original sharer.
