### ISSUE TITLE
[Feature-Request] Hide poll result until users have voted themselves

### ISSUE THREAD

**Issue by FackelAB** [nextcloud/polls#915]
It should be possible to create the poll in such a way that a user who has not yet cast a vote should not yet see the (current) result. This should only be displayed once the user has cast his vote.

**Comment by dartcafe** [comment]
@FackelAB I would like to understand the intention. Can you explain your request in the form of a user story? 

* As a poll creator, 
* I want that a user cannot see the results of a poll until he votes, 
* because ...

I ask because hiding poll results is not possible this way. As soon as a user clicks a single vote option, he counts a participant and the results will appear. Because of that the "because" of the user story is important to understand the value of this request.

**Comment by bpcurse** [comment]
My two cents:
If you see how other participants voted, it will probably bias you when casting your own vote.
This makes polls unsuitable for some scientific/social use cases. An important feature IMO.

**Comment by dartcafe** [comment]
@bpcurse You can hide the poll result permanently or until the poll expires since version 1.4, see #265. This issue is about hiding the poll until a user votes. But as soon, as he hits one vote option he counts as participant and the results are displayed. I guess, this is not what @FackelAB wants to achieve.

**Comment by bpcurse** [comment]
@dartcafe Maybe a misunderstanding. I understood @FackelAB's proposal as a variation of #893, by showing the results to each user after the individual vote, still hiding them from others who haven't voted yet.

**Comment by dartcafe** [comment]
That's what I understood too. But I am sure, it won't work as expected and that's the reason, why I want to understand the use case of this issue. 

Again: One click in a single vote option presents the result.

**Comment by bpcurse** [comment]
> Again: One click in a single vote option presents the result.

So the "problem" is, that there is auto-save instead of a "cast your vote button" and you therefore cannot define when to show the other participants' results and due to this it won't work as expected, correct?

Now I see your point. Thanks for your patience :)

**Comment by dartcafe** [comment]
Yes. And polls are changable everytime until closed.

**Comment by FackelAB** [comment]
Hi,

Gruß
            Timo

> Am 10.05.2020 um 16:29 schrieb René Gieling <notifications@github.com>:
> 
> ﻿
> @bpcurse You can hide the poll result permanently or until the poll expires since version 1.4, see #265. This issue is about hiding the poll until a user votes.
> 

> But as soon, as he hits one vote option he counts as participant and the results are displayed. I guess, this is not what @FackelAB wants to achieve.
> 
> —
> 
You are right - The results should be hidden until the user has chosen all options that he want to select or set on „may be“.
And after that the user should the the actual status of the poll. 

So the user could give his (first) without beging influenced by the current votes.

And with an option, that an user is not able to modify his votes in the future this would be really nice.

**Comment by dartcafe** [comment]
Sorry to say, but we will not see this feature in the near future. The app designed in another way. As I stated here (https://github.com/nextcloud/polls/issues/926#issuecomment-626351802) this is also beyound the scope of this app. 

You are still able to hide the results until the poll is closed. This is IMHO a good compromise to make thinks not more complex and achieve the goal, that a user is not biased or influenced by other votes in this poll.
