### ISSUE TITLE
Add AM/PM option to times

### ISSUE THREAD

**Issue by crobarcro** [nextcloud/polls#919]
It would be good to have a more generic AM option and PM option available as well as specific times for event scheduling.

App's great by the way though!

**Comment by dartcafe** [comment]
@crobarcro I don't understand your request. Can you give an example?

**Comment by crobarcro** [comment]
When you create a poll to agree a time for an event you must select a specific time, e.g. 10.00, 11.00 etc. Sometimes I only want a quick indication of whether respondents will be variable in the morning or the afternoon. In this case it would nice to be able have an option for AM, or just PM each day.

**Comment by v1r0x** [comment]
IMO that's not easy to implement/store in the db.
I'd suggest either
- select e.g. 10:00 and 20:00 and make in the description clear that it's only morning and afternoon/evening. That's how I do it in such cases.
- Or you can use a text poll, but that's more complex, because you have to enter each day am and pm as text.

**Comment by dartcafe** [comment]
I would rate this as an edge case and can be solved, in a way, which @v1r0x describes. At least, with developing #492 you will have a convinient alternative.
