### ISSUE TITLE
Change click order when "Maybe" is enabled

### ISSUE THREAD

**Issue by jacotec** [nextcloud/polls#920]
From my experience users who do not know the app in detail or are first-time users (mostly external ones), don't use it correctly when the option "Maybe" is enabled.

The click order gives you "Maybe" with the first click and "Yes" with the second click - 3 out of 3 external users in a poll just clicked the dates they are available and they were all set to "Maybe". I needed to tell them that they need to klick again.

In my opinion it would be better to have "Yes" as the first click choice and "Maybe" with the second click.

**Comment by dahumph** [comment]
Totally agree to what jacotec stated. Further I suggest to show a legend what the different symbols meanings are. No external user will recognize the yellow tick as a maybe.

**Comment by dartcafe** [comment]
> In my opinion it would be better to have "Yes" as the first click choice and "Maybe" with the second click.

That's how it should be. This is a bug.

**Comment by stefan123t** [comment]
Dear @dartcafe,

may I add that the empty choice should be part of the click order too ?

I find it frustrating that I have to delete a line as admin when someone inadvertently selected an option but would rather leave the vote empty instead of maybe.

An example would be a poll for how many places are left in a drivers car, here the empty is more significant than a cross / maybe checkbox.

Kind regards
Stefan
