### ISSUE TITLE
Providing better anonymity for polls

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/polls#926]
**Is your feature request related to a problem? Please describe.**
Follow-up to #925. As discussed in the before mentioned issue "anonymous polls" are only partially anonymous (or to be correct pseudonymous).

**Describe the solution you'd like**
Enhance anonymity by:
- offering an additional anonymous polls option that hides the names from everyone including the poll creator
- cannot be reverted once the first vote (except from the creator) has been cast
- users joining the poll through a link share shouldn't be asked for a name, instead a random string should be generated and used as in the individual link secret
- an info text should inform the participants, that this setting has been selected and what it does
- the list containing the votes should be reordered randomly, every time a new vote has been cast to prevent inference on individuals by sequence
- optionally only show other votes if there are e.g. at least 5 of them

**Comment by dartcafe** [comment]
I appreciate your effort in writing good understandable issues but this time a clear NO from me and I will explain why: 
* the intention of this poll is to get a commitment between people or to organize things like similar apps (i.e. doodle)
* the intention is not beeing an app to support elections or other confidential usage
* even surveys are not subject (the forms app addresses this use case)
* anonymity cannot be guaranteed by design
* we try to keep complexity low to keep maintainability possible
* the focus of this app should be UX, not security (or at least a good compromise) 

I think the current implementation is a good compromise.
