### ISSUE TITLE
Cannot delete comments of deleted users

### ISSUE THREAD

**Issue by Hk1020** [nextcloud/polls#999]
### What is going wrong?
**Describe the bug**
When a participant's entry and the participant's invitation are deleted by an admin comments made by said participant stay behind and cannot be deleted. There is no option to do so.

**To Reproduce**

1. Create a public poll.
1. Check _Allow admins to edit this poll_
1. Check _Visible to other users_
1. Check _Always show results_
1. Add a date option
1. Add a public link
1. Use public link to participate without being a nextcloud user
1. Check the poll option
1. Add a comment, close browser window
 As poll creator
1. Click the trash can on participants entry
1. On _Details_ tab select _Shares_
1. Click the trash can of the participant

Now the entry is gone but the comment stays behind and cannot be deleted.

**Expected behavior**
Need a trash can on the comment or the comment should go when the user is deleted.

**Screenshots**
![image](https://user-images.githubusercontent.com/1018004/86499193-17c2cb80-bd8a-11ea-8dda-b03bbb66f907.png)
![image](https://user-images.githubusercontent.com/1018004/86499199-201b0680-bd8a-11ea-86c5-58c77436416a.png)

### Information about your polls installation
**Polls version?** 1.4.3

**Fresh installation or update from a prior version (from which one)?**
Update

**How did you install this version?(Appstore or describe installation)**
From Appstore via Nextcloud admin web interface

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud or ownCloud?**
Nextcloud

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
18.0.6

**Comment by v1r0x** [comment]
I'd keep comments even when a user is removed from the poll. But an option to delete a comment would be helpful. What do you think @dartcafe ?

**Comment by dartcafe** [comment]
The reason, why currently the deleting of comments is limited to the author of the comment is, that it may feel like censorship. 

Actually I am not sure, what is right. Should the poll owner have the right to censor comments or should this right be reserved for the author?

What will participants say, if their comment vanish from the poll?
Which value is rated higher?

**Comment by Hk1020** [comment]
You could argue the same for the poll entry. The author can remove those already.

And then there is the deadlock that the author can remove the individual share (under Details -> Shares) which leaves a non-editable entry.

**Comment by dartcafe** [comment]
> You could argue the same for the poll entry.

Agree. I am fine with both solutions: Giving the owner the right to censor comments, as well as let them stay in the thread. 

I just want to avoid discussions after a possible implementation.

**Comment by tobyps** [comment]
In most cases it has nothing to do with censorship but with getting rid of involuntarily divulged information (ie names in anonymous and public polls) or incorrect information about the use of the poll. 
Those two are currently our issues in using it in a rather non tech savvy community...
It is not a dealbreaker not to have that feature but it would be rather nice.
 Especially because most users without account dont save their links.
I know I can access the link myself and probably delete the comment but that seems a rather clumsy way and does not work for logged in users

**Comment by tobyps** [comment]
In most cases it has nothing to do with censorship but with getting rid of involuntarily divulged information (ie names in anonymous and public polls) or incorrect information about the use of the poll. 
Those two are currently our issues in using it in a rather non tech savvy community...
It is not a dealbreaker not to have that feature but it would be rather nice.
 Especially because most users without account dont save their links.
I know I can access the link myself and probably delete the comment but that seems a rather clumsy way and does not work for logged in users.

**Comment by tobyps** [comment]
In most cases it has nothing to do with censorship but with getting rid of involuntarily divulged information (ie names in anonymous and public polls) or incorrect information about the use of the poll. 
Those two are currently our issues in using it in a rather non tech savvy community...
It is not a dealbreaker not to have that feature but it would be rather nice.
 Especially because most users without account dont save their links.
I know I can access the link myself and probably delete the comment but that seems a rather clumsy way and does not work for logged in users.

**Comment by tobyps** [comment]
In most cases it has nothing to do with censorship but with getting rid of involuntarily divulged information (ie names in anonymous and public polls) or incorrect information about the use of the poll. 
Those two are currently our issues in using it in a rather non tech savvy community...
It is not a dealbreaker not to have that feature but it would be rather nice.
 Especially because most users without account dont save their links.
I know I can access the link myself and probably delete the comment but that seems a rather clumsy way and does not work for logged in users.

**Comment by RolandBBerlin** [comment]
My use case for deletion of comments - at least for the poll owner - is more of a practical nature. I tried to use polls as a teacher in my classes. The comments section was found by the 9th graders and used with profane language. I had no ability to delete those unwanted comments or to disable comments at all.
Feels strange that for this use case I should have to use commercial platforms (i.e. doodle) where deletion of comments is possible.
Also, I can delete any specific answer in the poll, but not the comments, that may have led to these answers.

**Comment by dartcafe** [comment]
Since there are good reasons for allowing deletion, it is targeted for version 1.8. See PR
